services:
  redis:
    image: redis:7-alpine
    container_name: er_redis
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--appendfsync"
      - "everysec"
      - "--auto-aof-rewrite-percentage"
      - "100"
      - "--auto-aof-rewrite-min-size"
      - "64mb"
      - "--aof-use-rdb-preamble"
      - "yes"
    volumes:
      - er_redis_data:/data

  dev:
    build: .
    image: docker-dev
    container_name: er_dev
    depends_on:
      - redis
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - ER_REDIS_HOST=redis
      - ER_REDIS_PORT=6379
    volumes:
      - ..:/work
    tty: true

volumes:
  er_redis_data:

